[workspace]
authors = ["Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>"]
channels = ["conda-forge"]
name = "dra-ttt-course-pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
preview = { cmd = [
    "quarto",
    "preview",
    "--port",
    "8888",
] }


[dependencies]
quarto = ">=1.7.33,<2"
