name: quarto

on:
  push:
    branches:
      - main

jobs:
  quarto:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto render --output-dir public
      - name: Upload artifact to GitHub
        uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - name: Publish GitHub pages
        uses: actions/deploy-pages@v4