name: quarto

on: 
  branch: main

jobs:
  quarto:
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto render --output-dir public
      - name: Upload artifact to GitHub
        uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - name: Publish GitHub pages
        uses: actions/deploy-pages@v4